apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-bridge-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: my-bridge.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-bridge-bridge-service
            port: 
              number: 8080
